In [1]:
import numpy as np

In [3]:
uniform=np.random.rand(3,3)
print("Uniform Distridution:\n",uniform)

Uniform Distridution:
 [[0.34422564 0.12513328 0.58084491]
 [0.91290138 0.5691457  0.15245049]
 [0.29048329 0.51129741 0.4044643 ]]


In [37]:
#searching in array where----returns the index value 

In [9]:
a=np.array([1,2,3,4,5])

In [11]:
np.where(a>3)

(array([3, 4], dtype=int64),)

In [13]:
np.where(a>4)

(array([4], dtype=int64),)

In [15]:
np.where(a<2)

(array([0], dtype=int64),)

In [17]:
np.argmax(a)

4

In [19]:
np.argmin(a)

0

In [21]:
#searchsorted

In [23]:
sorted_arr=np.array([1,3,5,7])

In [25]:
np.searchsorted(sorted_arr,6)

3

In [27]:
np.searchsorted(sorted_arr,4)

2

In [35]:
#extract --- retuns the value 

In [33]:
np.extract(a>3,a)

array([4, 5])

In [39]:
#transpose

In [41]:
matrix=([[1,2,3],[4,5,6]])

In [43]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [45]:
np.transpose(matrix)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
#mean

In [51]:
print("Mean Value",np.mean(a))

Mean Value 3.0


In [53]:
#splitting arrays

In [55]:
#--equal parts split

In [57]:
aa=np.array([1,2,3,4,5,6])
np.split(aa,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [59]:
np.split(aa,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [61]:
#--split at specific positions

In [63]:
np.split(aa,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [65]:
#matrix

In [67]:
mat=np.array([[1,2,3],
              [4,5,6]])

In [69]:
np.split(mat, 3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [71]:
matr=np.array([[1,2,3,4],
              [5,6,7,8]])

In [73]:
np.split(matr,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [75]:
ab=np.array([3,1,2,4])
np.sort(ab)

array([1, 2, 3, 4])

In [79]:
matt=np.array([[3,1,2],
               [6,5,4]])

In [81]:
print("sorted rows:\n",np.sort(matt,axis=1))

sorted rows:
 [[1 2 3]
 [4 5 6]]


In [83]:
print("sorted columns:\n",np.sort(matt,axis=0))

sorted columns:
 [[3 1 2]
 [6 5 4]]
