In [1]:
#numpy

In [3]:
#array module

In [83]:
from array import array
my_array=('i',[2,5,7,8,6])

In [85]:
my_array 

('i', [2, 5, 7, 8, 6])

In [29]:
type(my_array)

array.array

In [15]:
#numpy arrays

In [19]:
import numpy as np

In [21]:
arr=np.array([1,2,3,4,5])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [25]:
type(arr)

numpy.ndarray

In [27]:
arr.ndim

1

In [31]:
arr.dtype

dtype('int32')

In [57]:
array_new = np.array([1,2,3,4,5])

In [53]:
array_new +3

array([4, 5, 6, 7, 8])

In [45]:
type(array_new)

numpy.ndarray

In [59]:
my_numpy_array=np.array([1,2,3,4,5])

In [61]:
new_array=my_numpy_array*3

In [63]:
new_array

array([ 3,  6,  9, 12, 15])

In [65]:
type(new_array)

numpy.ndarray

In [67]:
type(my_numpy_array)

numpy.ndarray

In [71]:
new_array>5

array([False,  True,  True,  True,  True])

In [87]:
matrix=np.array([
    [1,2,3],
    [4,3,5],
    [3,7,9]])

In [89]:
matrix

array([[1, 2, 3],
       [4, 3, 5],
       [3, 7, 9]])

In [99]:
arr_2d=np.array([[0,1,2],[3,4,5],[7,9,8]])

In [101]:
arr_2d*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [14, 18, 16]])

In [103]:
type(arr_2d)

numpy.ndarray

In [107]:
arr_2d.ndim

2

In [109]:
arr_2d+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 11, 10]])

In [111]:
arr_2d-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 6,  8,  7]])

In [113]:
arr_2d%2

array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0]], dtype=int32)

In [119]:
list_data = [1,6,5,7,9]
array_from_list=np.array(list_data)

In [121]:
list_data

[1, 6, 5, 7, 9]

In [127]:
type(list_data)

list

In [123]:
array_from_list

array([1, 6, 5, 7, 9])

In [125]:
type(array_from_list)

numpy.ndarray

In [129]:
array_from_list

array([1, 6, 5, 7, 9])