In [1]:
import numpy as np


In [13]:
arr=np.array([[1,2],
              [3,4]])
arr1=np.array([[5,6],
              [3,4]])

In [17]:
np.concatenate((arr,arr1),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [3, 4]])

In [19]:
np.concatenate((arr,arr1),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 3, 4]])

In [23]:
#stacks arrays vertically(row_wise)
arr2=np.array([1,2,3])
arr3=np.array([4,5,6])

In [25]:
np.vstack((arr2, arr3))

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a=np.array([1,2])
b=np.array([3,4])

In [29]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [31]:
#filtering

In [39]:
import numpy as np
aa=np.array([1,2,3,4,5,6])
mask=aa>3
filtered=aa[mask]
print("Filtered element >3:",filtered)

Filtered element >3: [4 5 6]


In [53]:
(aa>2)&(aa<6) #-------boolean

array([False, False,  True,  True,  True, False])

In [51]:
aa[(aa>2)&(aa<6)]    #------filtered

array([3, 4, 5])

In [47]:
aa[(aa<=3) | (aa>5)]

array([1, 2, 3, 6])

In [59]:
matrix=np.array([
    [10,15,20,],
    [25,30,35]
])
print("Values > 20:",matrix[matrix>20])

Values > 20: [25 30 35]


In [61]:
scores=np.array([85,92,78,88,95,72,89,94,68,90])

In [63]:
print("Scores values>90:",scores[scores>90])

Scores values>90: [92 95 94]


In [77]:
scores[(scores>70)  | (scores<80)]

array([85, 92, 78, 88, 95, 72, 89, 94, 68, 90])

In [79]:
import numpy as np


In [95]:
ab=np.arange(1,16)

In [97]:
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [99]:
ab[ab%3==0]    #------numbers that rae divisible by 3

array([ 3,  6,  9, 12, 15])

In [101]:
ab[ab%2==0]    #----even numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [105]:
ab[ab%2!=0]    #-----odd numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [138]:
import numpy as np
temp=np.array([22.5,19.0,25.6,21.4,29.9,18.6,23.1,27.0])
temp[temp>24]

array([25.6, 29.9, 27. ])

In [142]:
temp[(temp > 20)  & (temp < 26)]

array([22.5, 25.6, 21.4, 23.1])

In [146]:
prices=np.array([250,499,520,310,800,999,450,720])

In [150]:
prices[prices>500]

array([520, 800, 999, 720])