In [1]:
#creating numpy array

In [5]:
import numpy as np

In [17]:
a= np.ones((3,4))

In [19]:
type(a)

numpy.ndarray

In [21]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
a1=np.zeros((2,4))

In [25]:
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
zeros_array=np.zeros((3,3))

In [29]:
ones_array=np.ones((2,4))

In [35]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
identity_matrix=np.eye(3)

In [33]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
b=[1,2,3,4]

In [41]:
np.array(b,dtype=np.int32)

array([1, 2, 3, 4])

In [43]:
int_array=np.array([1,2,3], dtype=np.int32)
float_array=np.array([0.1,0.2,0.3],dtype=np.float64)

In [45]:
int_array

array([1, 2, 3])

In [47]:
float_array

array([0.1, 0.2, 0.3])

In [49]:
a2=np.arange(0,8)

In [51]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
linspace_array=np.linspace(0,10,6)

In [75]:
linspace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [89]:
linspace_array1=np.linspace(0,20,5)

In [91]:
linspace_array1

array([ 0.,  5., 10., 15., 20.])

In [103]:
random_array=np.random.rand(4,4)

In [105]:
random_array

array([[0.40671158, 0.22478629, 0.44981922, 0.91515954],
       [0.481726  , 0.4866366 , 0.11552403, 0.34252387],
       [0.7239913 , 0.16279796, 0.72181653, 0.36071176],
       [0.02697178, 0.53790672, 0.26139788, 0.73295563]])

In [107]:
#basic indexing

In [115]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [117]:
arr1=np.array([[23,4,6,3],[1,67,98,6]])

In [119]:
arr1

array([[23,  4,  6,  3],
       [ 1, 67, 98,  6]])

In [123]:
print(arr1[0,3])

3


In [125]:
print(arr1[1,-1])

6


In [127]:
#1D array slicing

In [137]:
arr2=np.array([1,7,8,5,4,3])
print(arr2[1:4])
print(arr2[:6])
print(arr2[:-1])

[7 8 5]
[1 7 8 5 4 3]
[1 7 8 5 4]


In [139]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [201]:
print(matrix[0:1,1:3])

[[2 3]]


In [153]:
print(matrix[2:3,1:2])

[[8]]


In [161]:
print(matrix[1:2,1:3])

[[5 6]]


In [167]:
v=np.array([1,2,3,4])

In [171]:
s=v[1:3]

In [173]:
s

array([2, 3])

In [189]:
#copy

In [191]:
a=np.array([1,2,3,4,5])

In [193]:
b=a[1:3].copy()

In [195]:
b

array([2, 3])

In [203]:
#shape

In [205]:
arr=np.array([[1,2,3],[4,5,6]])

In [207]:
arr.shape

(2, 3)

In [225]:
a=np.arange(12)

In [227]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [231]:
b=a.reshape(3,4)

In [233]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [235]:
d=np.arange(20)

In [237]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [239]:
e=d.reshape(5,4)

In [241]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [251]:
arr_3d=np.array([[0,1,2],
              [4,5,6],
              [7,8,9]])

In [253]:
arr_3d.transpose()

array([[0, 4, 7],
       [1, 5, 8],
       [2, 6, 9]])

In [255]:
arr=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])

In [257]:
arr.transpose()

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])